### ISSUE TITLE
想问一下作者rss有关__config__.py的问题

### ISSUE THREAD

**Issue by viper-sys** [mengshouer/HoshinoBot-Plugins#1]
我使用hoshinobot添加rss插件后，发现使用默认的__config__.py无法成功推送订阅信息，研究了一下看到里面的
API_ROOT = 'http://127.0.0.1:5700'
RSS_PROXY = '127.0.0.1:808'    # 代理地址
这两个地方是需要做什么样的修改才可以正常推送，以及现在如果不使用代理还可以通过rsshub来订阅b站动态吗

**Comment by mengshouer** [comment]
不用配置，默认就能用，b站也能正常推送。API_ROOT是反向ws填的值，RSS_PROXY的10809端口是V2rayN的默认端口，根据自己需求改，无法正常推送不知道是不是你访问不到rss链接，默认的rsshub.app是有DNS污染的，不过我也不推荐使用默认的rsshub.app，缓存起码1小时，推送的话出现新内容起码要1小时之后才能更新。至于其他rss地址，随便百度就有了。

**Comment by viper-sys** [comment]
多谢作者 我再去研究一下
