### ISSUE TITLE
superuser 新建订阅  "user_id"字段为空

### ISSUE THREAD

**Issue by dfmjndm** [mengshouer/HoshinoBot-Plugins#15]
superuser 新建订阅  "user_id"字段为空

"user_id": []

**Comment by mengshouer** [comment]
我这里测试正常

**Comment by mengshouer** [comment]
需要更多信息

**Comment by dfmjndm** [comment]
user = (
    str(session.ctx["user_id"])
    if session.ctx["message_type"] == "private"
    else None
)

对于非私聊信息就是用的None
