### ISSUE TITLE
是否有程序在初始化的时候删掉rss.json中的group字段的可能

### ISSUE THREAD

**Issue by dfmjndm** [mengshouer/HoshinoBot-Plugins#16]
是否有程序在初始化的时候删掉rss.json中的group字段的可能
最近发现一些原本有group字段的配置在重启后group字段被移除
进而触发××××[https://××××]无人订阅！已自动停止更新！

**Comment by mengshouer** [comment]
代码应该不是初始化的时候删掉的，运行的时候如果中途bot掉线了，没扫到群组，好像就会被删了

印象中遇到过，不过那时候打算换框架了就没管了（ 我现在都在把插件往 nonebot2 和 koishi 迁移了，hoshino本体不更新，nonebot1也早停更了，加上现在看来 onebot 也不是以后的趋势，就想换掉了
