### ISSUE TITLE
RSShub copymanga系列路由无法更新

### ISSUE THREAD

**Issue by IsaacTheMouse** [mengshouer/HoshinoBot-Plugins#9]
测试时的例子：
名称：test
订阅地址：/copymanga/comic/zhanlizhensuo?limit=3

> [2022-06-03 03:57:46,881 nonebot] INFO: test 检查更新
> Job "check_update (trigger: interval[0:01:00], next run at: 2022-06-03 03:58:50 CST)" raised an exception
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.8/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
>     retval = await job.func(*job.args, **job.kwargs)
>   File "/home/ubuntu/Hoshino/hoshino/modules/rss2/my_trigger.py", line 20, in check_update
>     await asyncio.wait_for(rss_parsing.start(rss), timeout=wait_for)
>   File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
>     return fut.result()
>   File "/home/ubuntu/Hoshino/hoshino/modules/rss2/rss_parsing.py", line 73, in start
>     await pr.start(rss_name=rss.name, new_rss=new_rss)
>   File "/home/ubuntu/Hoshino/hoshino/modules/rss2/parsing/parsing_rss.py", line 163, in start
>     self.state.update(await handler.func(rss=self.rss, state=self.state))
>   File "/home/ubuntu/Hoshino/hoshino/modules/rss2/parsing/routes/nga.py", line 20, in handle_check_update
>     change_data = check_update(db, new_data)
>   File "/home/ubuntu/Hoshino/hoshino/modules/rss2/parsing/routes/nga.py", line 33, in check_update
>     old_link_list = [i["id"] for i in db.all()]
>   File "/home/ubuntu/Hoshino/hoshino/modules/rss2/parsing/routes/nga.py", line 33, in <listcomp>
>     old_link_list = [i["id"] for i in db.all()]
> KeyError: 'id'

第一次能正常获取RSS内容到json里，但是后续再有更新就写不进去。
~~我是不是应该去ELF那边提issue~~

**Comment by mengshouer** [comment]
rsshub路由的问题，这路由 status都down了

**Comment by IsaacTheMouse** [comment]
RSShub文档里给的举例会down是因为那本漫画没了啦。。。
https://rsshub.app/copymanga/comic/zhanlizhensuo?limit=3
是能正常获取的。

**Comment by mengshouer** [comment]
是ELF_RSS的问题，我修一下
